name: rs_tools
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Standard Libraries
  - numpy # Numerical Linear Algebra
  - scipy # Scientific Computing
  - scikit-image
  - conda-forge::xarray
  - conda-forge::rioxarray
  - conda-forge::goes2go
  - conda-forge::earthaccess
  - conda-forge::pyinterp
  - conda-forge::torchgeo
  - conda-forge::earthaccess
  - conda-forge::satpy
  - eumetsat::eumdac
  - pandas # Data structure
  - scikit-learn # Machine Learning
  - joblib # Parallelization
  # PLOTTING LIBRARY
  - matplotlib # standard plotting library
  - seaborn # Stats viz library
  - conda-forge::hvplot
  # Storage
  - conda-forge::netCDF4
  - conda-forge::zarr
  - conda-forge::h5netcdf
  - h5py
  # GUI
  - conda-forge::ipywidgets
  - ipykernel
  - conda-forge::tqdm
  - pip
  - pip:
      - toolz
      - typer
      - einops
      - cartopy
      # formatting
      - rasterio
      - black
      - pylint
      - isort
      - flake8
      - mypy
      - pytest
      - pre-commit
      # Notebook stuff
      - autoroot
      - pyprojroot
      - python-dotenv
      # logging
      - loguru
      # plotting
      - celluloid
      - corner
      - tabulate
      # experiment
      - hydra-core
      - hydra-zen
      # Docs
      - mkdocs-gen-files
      - mkdocs-literate-nav
      - mkdocs-git-authors-plugin
      - mkdocstrings
      - markdown-katex
      - pytkdocs
      - mdx-truly-sane-lists
      - mkdocs-jupyter
      - mkdocs-bibtex
      - pygments
      - mknotebooks
      - pymdown-extensions
      - mkdocs-material 
      - mkdocs
      - aiohttp
      # ITI
      - git+https://github.com/spaceml-org/InstrumentToInstrument.git@development